CREATE TABLE IF NOT EXISTS predictions (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    input_payload JSONB NOT NULL,
    output_payload JSONB NOT NULL,
    model_version TEXT
);

CREATE TABLE IF NOT EXISTS employee_attrition_dataset (
    id_employee INTEGER,
    age INTEGER,
    genre TEXT,
    revenu_mensuel DOUBLE PRECISION,
    statut_marital TEXT,
    departement TEXT,
    poste TEXT,
    nombre_experiences_precedentes INTEGER,
    nombre_heures_travailless INTEGER,
    annee_experience_totale INTEGER,
    annees_dans_l_entreprise INTEGER,
    annees_dans_le_poste_actuel INTEGER,
    satisfaction_employee_environnement INTEGER,
    note_evaluation_precedente INTEGER,
    niveau_hierarchique_poste INTEGER,
    satisfaction_employee_nature_travail INTEGER,
    satisfaction_employee_equipe INTEGER,
    satisfaction_employee_equilibre_pro_perso INTEGER,
    note_evaluation_actuelle INTEGER,
    heure_supplementaires TEXT,
    augementation_salaire_precedente TEXT,
    a_quitte_l_entreprise TEXT,
    nombre_participation_pee INTEGER,
    nb_formations_suivies INTEGER,
    nombre_employee_sous_responsabilite INTEGER,
    distance_domicile_travail DOUBLE PRECISION,
    niveau_education INTEGER,
    domaine_etude TEXT,
    ayant_enfants TEXT,
    frequence_deplacement TEXT,
    annees_depuis_la_derniere_promotion INTEGER,
    annes_sous_responsable_actuel INTEGER
);